---
- name: Add zypper repository
  become: true
  zypper_repository:
    name: "{{ item.key }}"
    repo: "{{ item.value }}"
    state: present
    disable_gpg_check: yes
  with_dict: "{{ zypper_repos }}"

# Install some useful tools
- name: Install basic packages with zypper
  become: true
  zypper:
    name: "{{item}}"
    state: present
  with_items:
    - less
    - vim
    - dos2unix
    - iftop
    - iotop
    - ntp
    - mc

- name: Configure NTP service
  become: true
  lineinfile:
    dest: /etc/ntp.conf
    state: present
    line: "server {{ item }} iburst"
  with_items: "{{ ntp_servers }}"
  notify:
    - restart ntp

- name: Enable NTP service
  become: true
  service:
    name: "{{ ntp_service_name }}"
    enabled: yes
    state: restarted
  when: ntp_servers|length > 0
